### PR TITLE
feat: allow custom tabs

### LINKED ISSUE #49: Is it possible to update the tab associated to a node ?
Hi, great lib :) 

I created a custom node, which needs configuration, pretty close to the Function node.
I was searching how to implement a custom Tab when I found these lines : 
https://github.com/gorules/jdm-editor/blob/a3ea6e6a9a09a57a75a4a786b2cdd909e8c07098/packages/jdm-editor/src/components/decision-graph/dg-wrapper.tsx#L71C1-L75C15

So it seems like it is not possible.
Do you plan to implement custom Tabs in the DecisionGraph props ? If not, would you accept a PR implementing this feature ?

### PR DESCRIPTION
**Pull request by Sangrene**
This PR adds support for custom tabs following this type:
```typescript
export type Tab = { type: string; tab: (p: CommonTabProps) => ReactNode };
```
`type` being the Node type that should be updated.

I also added a story for this.

Should fix #49 .

### CODE REVIEW

**Comment by stefan-gorules** [comment]
Code looks good, we'll just have to run a few tests on our side and you can expect this to be approved early next week.

Appreciate the contribution!

**Comment by Sangrene** [comment]
Any news on this @ivanmiletic @stefan-gorules ? 
Thanks

**Comment by ivanmiletic** [comment]
Hi @Sangrene was taking a look at this, as we are moving to a direction of a node specification we would like to have tabs part of a node specification.

Example you define node and you define its own tab and it will allow us to open tab for that specific node.

As we are doing a few big features in parallel, we will have time to tackle this end of next week.

**Comment by Sangrene** [comment]
I totally agree with that architecture change, I wanted to do it but felt like following the current architecture was more important :)

**Comment by ivanmiletic** [comment]
Solved via: https://github.com/gorules/jdm-editor/pull/118

**Pull request closed without merging**
